[package]
name = "ncmd"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.38"
clap = { version = "4.5.9", features = ["derive"] }
indexmap = "2.2.6"
walkdir = "2.5.0"
